In [1]:
import PyPDF2 as ppy
from addClass import main as ac
from addStudent import main as ass
from addStudClass import main as asc
import pandas as pd
import textract
import pymysql

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/compat/_optional.py:106: UserWarning: Pandas requires version '1.2.1' or newer of 'bottleneck' (version '1.0.0' currently installed).
  warnings.warn(msg, UserWarning)

In [2]:
pdf = ppy.PdfFileReader("./Transcript for Robi.pdf")
pdf2 = ppy.PdfFileReader("UWUnofficialTranscript.pdf")
text = textract.process("UWUnofficialTranscript.pdf")
otherPDF = text.decode("utf-8")

In [ ]:
import pymysql
import sys


rds_host  = "eatmyass.czvhjizhxvs4.us-west-2.rds.amazonaws.com"
name = "eatmyass"
password = "eatmyasspassword"
db_name = "eatmyass"

In [ ]:
event = {
    'Dept': 'PHIL',
    'ClassNum': '149'
}

In [ ]:
conn = pymysql.connect(rds_host, user=name, passwd=password, db=db_name, connect_timeout=5)

In [19]:
data = getClasses(pdf)
studentID = data['studentID']
data = data['data']
data

   Quarter Department ClassNum             ClassTitle  Grade  Year
0   AUTUMN     HSTLAC      185    LATIN AMER SOC/HIST    3.6  2018
1   AUTUMN       MATH      124  DL-CALC ANALYT GEOM I    1.7  2018
2   AUTUMN      PSYCH      101         INTRO TO PSYCH    3.0  2018
3   WINTER       ECON      200        INTRO MICROECON    3.6  2019
4   WINTER      ENTRE      459    W-VENTURE INVESTING    3.6  2019
5   WINTER        ESS      101      GEOLOGY & SOCIETY    3.8  2019
6   SPRING      ACCTG      215    ACCTG & FIN REPRTNG    2.7  2019
7   SPRING       ECON      201        INTRO MACROECON    2.9  2019
8   SPRING       ENGL      131    COMPOSITN: EXPOSITN    3.9  2019
9   AUTUMN      ACCTG      225       MANAGERIAL ACCTG    2.6  2019
10  AUTUMN      QMETH      201    INTRO TO STAT MTHDS    2.7  2019
11  AUTUMN      SCAND      100      INTRO SCANDINAVIA    4.0  2019
12  WINTER      DRAMA      101       INTRO TO THEATRE    4.0  2020
13  WINTER       MATH      124     CALC ANALYT GEOM I  3.2/R  2020
14  WINTER      SCAND      270       SAGAS OF VIKINGS    4.0  2020
15  SPRING       ECON      300    INTERMED MICRO-ECON     IP  2020
16  SPRING        SOC      371            CRIMINOLOGY     IP  2020
17  SPRING       STAT      311    ELEMNTS STAT METHOD     IP  2020
18  SPRING      ENTRE      499     UNDERGRAD RESEARCH     IP  2020

In [ ]:
studentID

In [20]:
def commitData(data, studentID):
    classes=data
#     studentID = data['studentID']
#     if (studentID == userID):     
    for i in range(len(classes)):
        row = data.loc[i]
        classEvent = {'Dept': row['Department'], 'ClassNum' : row['ClassNum'], 'ClassDesc' :  row['ClassTitle']}
        ac.main(classEvent)
        asc.main({'classEvent':classEvent, 'StudentID': studentID, 'Quarter': row['Quarter'], 'Year': row['Year'] })

In [22]:
data.loc[0]

Quarter                    AUTUMN
Department                 HSTLAC
ClassNum                      185
ClassTitle    LATIN AMER SOC/HIST
Grade                         3.6
Year                         2018
Name: 0, dtype: object

In [21]:
commitData(data, 112356)

(1, 'LATIN AMER SOC/HIST', 185, 'HSTLAC')
{'Dept': 'HSTLAC', 'ClassNum': '185', 'ClassDesc': 'LATIN AMER SOC/HIST'}
(112356, 'Big', 'Boi')
(1, 'LATIN AMER SOC/HIST', 185, 'HSTLAC')
(2, 'DL-CALC ANALYT GEOM I', 124, 'MATH')
{'Dept': 'MATH', 'ClassNum': '124', 'ClassDesc': 'DL-CALC ANALYT GEOM I'}
(112356, 'Big', 'Boi')
(1, 'LATIN AMER SOC/HIST', 185, 'HSTLAC')
(2, 'DL-CALC ANALYT GEOM I', 124, 'MATH')
(3, 'INTRO TO PSYCH', 101, 'PSYCH')
{'Dept': 'PSYCH', 'ClassNum': '101', 'ClassDesc': 'INTRO TO PSYCH'}
(112356, 'Big', 'Boi')
(1, 'LATIN AMER SOC/HIST', 185, 'HSTLAC')
(2, 'DL-CALC ANALYT GEOM I', 124, 'MATH')
(3, 'INTRO TO PSYCH', 101, 'PSYCH')
(4, 'INTRO MICROECON', 200, 'ECON')
{'Dept': 'ECON', 'ClassNum': '200', 'ClassDesc': 'INTRO MICROECON'}
(112356, 'Big', 'Boi')
(1, 'LATIN AMER SOC/HIST', 185, 'HSTLAC')
(2, 'DL-CALC ANALYT GEOM I', 124, 'MATH')
(3, 'INTRO TO PSYCH', 101, 'PSYCH')
(4, 'INTRO MICROECON', 200, 'ECON')
(5, 'W-VENTURE INVESTING', 459, 'ENTRE')
{'Dept': 'ENTRE', 'ClassNum': '459', 'ClassDesc': 'W-VENTURE INVESTING'}
(112356, 'Big', 'Boi')
(1, 'LATIN AMER SOC/HIST', 185, 'HSTLAC')
(2, 'DL-CALC ANALYT GEOM I', 124, 'MATH')
(3, 'INTRO TO PSYCH', 101, 'PSYCH')
(4, 'INTRO MICROECON', 200, 'ECON')
(5, 'W-VENTURE INVESTING', 459, 'ENTRE')
(6, 'GEOLOGY & SOCIETY', 101, 'ESS')
{'Dept': 'ESS', 'ClassNum': '101', 'ClassDesc': 'GEOLOGY & SOCIETY'}
(112356, 'Big', 'Boi')
(1, 'LATIN AMER SOC/HIST', 185, 'HSTLAC')
(2, 'DL-CALC ANALYT GEOM I', 124, 'MATH')
(3, 'INTRO TO PSYCH', 101, 'PSYCH')
(4, 'INTRO MICROECON', 200, 'ECON')
(5, 'W-VENTURE INVESTING', 459, 'ENTRE')
(6, 'GEOLOGY & SOCIETY', 101, 'ESS')
(7, 'ACCTG & FIN REPRTNG', 215, 'ACCTG')
{'Dept': 'ACCTG', 'ClassNum': '215', 'ClassDesc': 'ACCTG & FIN REPRTNG'}
(112356, 'Big', 'Boi')
(1, 'LATIN AMER SOC/HIST', 185, 'HSTLAC')
(2, 'DL-CALC ANALYT GEOM I', 124, 'MATH')
(3, 'INTRO TO PSYCH', 101, 'PSYCH')
(4, 'INTRO MICROECON', 200, 'ECON')
(5, 'W-VENTURE INVESTING', 459, 'ENTRE')
(6, 'GEOLOGY & SOCIETY', 101, 'ESS')
(7, 'ACCTG & FIN REPRTNG', 215, 'ACCTG')
(8, 'INTRO MACROECON', 201, 'ECON')
{'Dept': 'ECON', 'ClassNum': '201', 'ClassDesc': 'INTRO MACROECON'}
(112356, 'Big', 'Boi')
(1, 'LATIN AMER SOC/HIST', 185, 'HSTLAC')
(2, 'DL-CALC ANALYT GEOM I', 124, 'MATH')
(3, 'INTRO TO PSYCH', 101, 'PSYCH')
(4, 'INTRO MICROECON', 200, 'ECON')
(5, 'W-VENTURE INVESTING', 459, 'ENTRE')
(6, 'GEOLOGY & SOCIETY', 101, 'ESS')
(7, 'ACCTG & FIN REPRTNG', 215, 'ACCTG')
(8, 'INTRO MACROECON', 201, 'ECON')
(9, 'COMPOSITN: EXPOSITN', 131, 'ENGL')
{'Dept': 'ENGL', 'ClassNum': '131', 'ClassDesc': 'COMPOSITN: EXPOSITN'}
(112356, 'Big', 'Boi')
(1, 'LATIN AMER SOC/HIST', 185, 'HSTLAC')
(2, 'DL-CALC ANALYT GEOM I', 124, 'MATH')
(3, 'INTRO TO PSYCH', 101, 'PSYCH')
(4, 'INTRO MICROECON', 200, 'ECON')
(5, 'W-VENTURE INVESTING', 459, 'ENTRE')
(6, 'GEOLOGY & SOCIETY', 101, 'ESS')
(7, 'ACCTG & FIN REPRTNG', 215, 'ACCTG')
(8, 'INTRO MACROECON', 201, 'ECON')
(9, 'COMPOSITN: EXPOSITN', 131, 'ENGL')
(10, 'MANAGERIAL ACCTG', 225, 'ACCTG')
{'Dept': 'ACCTG', 'ClassNum': '225', 'ClassDesc': 'MANAGERIAL ACCTG'}
(112356, 'Big', 'Boi')
(1, 'LATIN AMER SOC/HIST', 185, 'HSTLAC')
(2, 'DL-CALC ANALYT GEOM I', 124, 'MATH')
(3, 'INTRO TO PSYCH', 101, 'PSYCH')
(4, 'INTRO MICROECON', 200, 'ECON')
(5, 'W-VENTURE INVESTING', 459, 'ENTRE')
(6, 'GEOLOGY & SOCIETY', 101, 'ESS')
(7, 'ACCTG & FIN REPRTNG', 215, 'ACCTG')
(8, 'INTRO MACROECON', 201, 'ECON')
(9, 'COMPOSITN: EXPOSITN', 131, 'ENGL')
(10, 'MANAGERIAL ACCTG', 225, 'ACCTG')
(11, 'INTRO TO STAT MTHDS', 201, 'QMETH')
{'Dept': 'QMETH', 'ClassNum': '201', 'ClassDesc': 'INTRO TO STAT MTHDS'}
(112356, 'Big', 'Boi')
(1, 'LATIN AMER SOC/HIST', 185, 'HSTLAC')
(2, 'DL-CALC ANALYT GEOM I', 124, 'MATH')
(3, 'INTRO TO PSYCH', 101, 'PSYCH')
(4, 'INTRO MICROECON', 200, 'ECON')
(5, 'W-VENTURE INVESTING', 459, 'ENTRE')
(6, 'GEOLOGY & SOCIETY', 101, 'ESS')
(7, 'ACCTG & FIN REPRTNG', 215, 'ACCTG')
(8, 'INTRO MACROECON', 201, 'ECON')
(9, 'COMPOSITN: EXPOSITN', 131, 'ENGL')
(10, 'MANAGERIAL ACCTG', 225, 'ACCTG')
(11, 'INTRO TO STAT MTHDS', 201, 'QMETH')
(12, 'INTRO SCANDINAVIA', 100, 'SCAND')
{'Dept': 'SCAND', 'ClassNum': '100', 'ClassDesc': 'INTRO SCANDINAVIA'}
(112356, 'Big', 'Boi')
(1, 'LATIN AMER SOC/HIST', 185, 'HSTLAC')
(2, 'DL-CALC ANALYT GEOM I', 124, 'MATH')
(3, 'INTRO TO PSYCH', 101, 'PSYCH')
(4, 'INTRO MICROECON', 200, 'ECON')
(5, 'W-VENTURE INVESTING', 459, 'ENTRE')
(6, 'GEOLOGY & SOCIETY', 101, 'ESS')
(7, 'ACCTG & FIN REPRTNG', 215, 'ACCTG')
(8, 'INTRO MACROECON', 201, 'ECON')
(9, 'COMPOSITN: EXPOSITN', 131, 'ENGL')
(10, 'MANAGERIAL ACCTG', 225, 'ACCTG')
(11, 'INTRO TO STAT MTHDS', 201, 'QMETH')
(12, 'INTRO SCANDINAVIA', 100, 'SCAND')
(13, 'INTRO TO THEATRE', 101, 'DRAMA')
{'Dept': 'DRAMA', 'ClassNum': '101', 'ClassDesc': 'INTRO TO THEATRE'}
(112356, 'Big', 'Boi')
Class Already Exists
{'Dept': 'MATH', 'ClassNum': '124', 'ClassDesc': 'CALC ANALYT GEOM I'}
(112356, 'Big', 'Boi')
(1, 'LATIN AMER SOC/HIST', 185, 'HSTLAC')
(2, 'DL-CALC ANALYT GEOM I', 124, 'MATH')
(3, 'INTRO TO PSYCH', 101, 'PSYCH')
(4, 'INTRO MICROECON', 200, 'ECON')
(5, 'W-VENTURE INVESTING', 459, 'ENTRE')
(6, 'GEOLOGY & SOCIETY', 101, 'ESS')
(7, 'ACCTG & FIN REPRTNG', 215, 'ACCTG')
(8, 'INTRO MACROECON', 201, 'ECON')
(9, 'COMPOSITN: EXPOSITN', 131, 'ENGL')
(10, 'MANAGERIAL ACCTG', 225, 'ACCTG')
(11, 'INTRO TO STAT MTHDS', 201, 'QMETH')
(12, 'INTRO SCANDINAVIA', 100, 'SCAND')
(13, 'INTRO TO THEATRE', 101, 'DRAMA')
(14, 'SAGAS OF VIKINGS', 270, 'SCAND')
{'Dept': 'SCAND', 'ClassNum': '270', 'ClassDesc': 'SAGAS OF VIKINGS'}
(112356, 'Big', 'Boi')
(1, 'LATIN AMER SOC/HIST', 185, 'HSTLAC')
(2, 'DL-CALC ANALYT GEOM I', 124, 'MATH')
(3, 'INTRO TO PSYCH', 101, 'PSYCH')
(4, 'INTRO MICROECON', 200, 'ECON')
(5, 'W-VENTURE INVESTING', 459, 'ENTRE')
(6, 'GEOLOGY & SOCIETY', 101, 'ESS')
(7, 'ACCTG & FIN REPRTNG', 215, 'ACCTG')
(8, 'INTRO MACROECON', 201, 'ECON')
(9, 'COMPOSITN: EXPOSITN', 131, 'ENGL')
(10, 'MANAGERIAL ACCTG', 225, 'ACCTG')
(11, 'INTRO TO STAT MTHDS', 201, 'QMETH')
(12, 'INTRO SCANDINAVIA', 100, 'SCAND')
(13, 'INTRO TO THEATRE', 101, 'DRAMA')
(14, 'SAGAS OF VIKINGS', 270, 'SCAND')
(15, 'INTERMED MICRO-ECON', 300, 'ECON')
{'Dept': 'ECON', 'ClassNum': '300', 'ClassDesc': 'INTERMED MICRO-ECON'}
(112356, 'Big', 'Boi')
(1, 'LATIN AMER SOC/HIST', 185, 'HSTLAC')
(2, 'DL-CALC ANALYT GEOM I', 124, 'MATH')
(3, 'INTRO TO PSYCH', 101, 'PSYCH')
(4, 'INTRO MICROECON', 200, 'ECON')
(5, 'W-VENTURE INVESTING', 459, 'ENTRE')
(6, 'GEOLOGY & SOCIETY', 101, 'ESS')
(7, 'ACCTG & FIN REPRTNG', 215, 'ACCTG')
(8, 'INTRO MACROECON', 201, 'ECON')
(9, 'COMPOSITN: EXPOSITN', 131, 'ENGL')
(10, 'MANAGERIAL ACCTG', 225, 'ACCTG')
(11, 'INTRO TO STAT MTHDS', 201, 'QMETH')
(12, 'INTRO SCANDINAVIA', 100, 'SCAND')
(13, 'INTRO TO THEATRE', 101, 'DRAMA')
(14, 'SAGAS OF VIKINGS', 270, 'SCAND')
(15, 'INTERMED MICRO-ECON', 300, 'ECON')
(16, 'CRIMINOLOGY', 371, 'SOC')
{'Dept': 'SOC', 'ClassNum': '371', 'ClassDesc': 'CRIMINOLOGY'}
(112356, 'Big', 'Boi')
(1, 'LATIN AMER SOC/HIST', 185, 'HSTLAC')
(2, 'DL-CALC ANALYT GEOM I', 124, 'MATH')
(3, 'INTRO TO PSYCH', 101, 'PSYCH')
(4, 'INTRO MICROECON', 200, 'ECON')
(5, 'W-VENTURE INVESTING', 459, 'ENTRE')
(6, 'GEOLOGY & SOCIETY', 101, 'ESS')
(7, 'ACCTG & FIN REPRTNG', 215, 'ACCTG')
(8, 'INTRO MACROECON', 201, 'ECON')
(9, 'COMPOSITN: EXPOSITN', 131, 'ENGL')
(10, 'MANAGERIAL ACCTG', 225, 'ACCTG')
(11, 'INTRO TO STAT MTHDS', 201, 'QMETH')
(12, 'INTRO SCANDINAVIA', 100, 'SCAND')
(13, 'INTRO TO THEATRE', 101, 'DRAMA')
(14, 'SAGAS OF VIKINGS', 270, 'SCAND')
(15, 'INTERMED MICRO-ECON', 300, 'ECON')
(16, 'CRIMINOLOGY', 371, 'SOC')
(17, 'ELEMNTS STAT METHOD', 311, 'STAT')
{'Dept': 'STAT', 'ClassNum': '311', 'ClassDesc': 'ELEMNTS STAT METHOD'}
(112356, 'Big', 'Boi')
(1, 'LATIN AMER SOC/HIST', 185, 'HSTLAC')
(2, 'DL-CALC ANALYT GEOM I', 124, 'MATH')
(3, 'INTRO TO PSYCH', 101, 'PSYCH')
(4, 'INTRO MICROECON', 200, 'ECON')
(5, 'W-VENTURE INVESTING', 459, 'ENTRE')
(6, 'GEOLOGY & SOCIETY', 101, 'ESS')
(7, 'ACCTG & FIN REPRTNG', 215, 'ACCTG')
(8, 'INTRO MACROECON', 201, 'ECON')
(9, 'COMPOSITN: EXPOSITN', 131, 'ENGL')
(10, 'MANAGERIAL ACCTG', 225, 'ACCTG')
(11, 'INTRO TO STAT MTHDS', 201, 'QMETH')
(12, 'INTRO SCANDINAVIA', 100, 'SCAND')
(13, 'INTRO TO THEATRE', 101, 'DRAMA')
(14, 'SAGAS OF VIKINGS', 270, 'SCAND')
(15, 'INTERMED MICRO-ECON', 300, 'ECON')
(16, 'CRIMINOLOGY', 371, 'SOC')
(17, 'ELEMNTS STAT METHOD', 311, 'STAT')
(18, 'UNDERGRAD RESEARCH', 499, 'ENTRE')

{'Dept': 'ENTRE', 'ClassNum': '499', 'ClassDesc': 'UNDERGRAD RESEARCH'}
(112356, 'Big', 'Boi')

In [ ]:
ac.main(classEvent)

In [ ]:
data.loc[0]

In [4]:
def mergePages(pages):
    breaks = []
    total = []
    # Look for the word 'Page' on each page 
    # assumptions: there is only one occurance
    # no valuable data preceds the occurance of 'Page'
    curQtr = ""
    studentNumber = ""
    for i in range(pages.getNumPages()):
        page = pages.getPage(i)
        parsed = page.extractText().split('\n')
        studentNumber = parsed[8]
        for i,x in enumerate(parsed):
            if "Page" in x:
                breaks = i
            if 'CURRENTLY ENROLLED' in x:
                curQtr = x.split('(')[1].split(')')[0].replace('QUARTER, ', "")        
        useful = parsed[breaks + 1: ]
        total.extend(useful)
    return {'total': total, 'curQtr': curQtr.strip(), 'studentID': studentNumber}

In [17]:
def getClasses(pdf):
    information = mergePages(pdf)
    parsed = information['total']
    curQtr = information['curQtr']
    studentID = information['studentID']
    durations = pd.DataFrame(columns = ['Quarter', 'Year', 'StatusWhile', 'index'])
    count = 0
    for i, x in enumerate(parsed):
        if 'AUTUMN' in x or 'WINTER' in x or 'SPRING' in x and 'D E S T R O Y' not in x:
            row = {'Quarter': x.split()[0], 'Year': x.split()[1], 'StatusWhile' : x.split()[2], 'index': i}
    #         y = x.split()
            durations = durations.append(row, ignore_index=True)
            count = count +1

    classes = pd.DataFrame(columns = ['Quarter', 'Department', 'ClassNum', 'ClassTitle', 'Grade'])
    for i in durations.iloc:
        ind = i['index'] + 1
        cur = parsed[ind]
        while 'QTR' not in cur and 'EARNED' not in cur and 'D E S T R O Y' not in cur and ind < len(parsed):
            if 'GEN ST' in cur:
                cur = cur.replace('GEN ST' ,"GEN")
            curSplit = cur.split()
            desc = ""
            grade =  curSplit[-1]
            for j in range(2, len(curSplit) - 2):
                desc = desc + " " + curSplit[j]
            if curQtr == str(i['Quarter'] + " " +i['Year']):
                desc = ""
                for j in range(2, len(curSplit) - 1):
                    desc = desc + " " + curSplit[j]
                grade = "IP"
            row = {'Quarter': i['Quarter'].strip(), 'Year': i['Year'].strip(), 'Grade': grade.strip(), 'Department': curSplit[0].strip(), 'ClassNum': curSplit[1].strip(), 'ClassTitle' : desc.strip() }
            classes = classes.append(row, ignore_index=True)
            ind = ind + 1
            cur = parsed[ind]
            
    return {'data': classes, 'studentID': studentID}

In [ ]:
parsed = pdf2.getPage(0).extractText().split('\n')
parsed[8]

In [11]:
rds_host  = "eatmyass.czvhjizhxvs4.us-west-2.rds.amazonaws.com"
name = "eatmyass"
password = "eatmyasspassword"
db_name = "eatmyass"

In [ ]:
cur.execute("""insert into tbl_studClass (StudentID, Quarter, ClassID) values( '%s', '%s', (Select ClassID from tbl_classes WHERE ClassNum = '%s' and Dept = '%s' and ClassDesc = '%s' ))""" % ( event['StudentID'], event['Quarter'], classEvent['ClassNum'], classEvent['Dept'], classEvent['ClassDesc'] ))
cur.execute("""select * from tbl_students""")
conn.commit()
cur.close()

In [ ]:
conn = pymysql.connect(rds_host, user=name, passwd=password, db=db_name, connect_timeout=5)
with conn.cursor() as cur:
    cur.execute("""insert into tbl_studClass (StudentID, Quarter, ClassID) values( '%s', '%s', (Select ClassID from tbl_classes WHERE ClassNum = %s and Dept = '%s' and ClassDesc like '%s' ))""" % ( 112356, 'AUTUMN', 499, 'ENTRE', '%UNDERGRAD RESEARCH%' ))
    cur.execute("""select * from tbl_students""")
    conn.commit()
    for row in cur:
        print(row)
    cur.close()

In [9]:
event = {'Dept': 'MATH', 'ClassNum': '124', 'ClassDesc': ' CALC ANALYT GEOM I'}

In [14]:
conn = pymysql.connect(rds_host, user=name, passwd=password, db=db_name, connect_timeout=5)
with conn.cursor() as cur:
    cur.execute("""select ClassID from tbl_classes where Dept = 'MATH' and ClassNum = '124' and 'ClassDesc' = 'CALC ANALYT GEOM I' """)
    conn.commit()
    print(cur.fetchone())
    cur.close()

None